language: node_js
node_js: 
  - "10"
before_script:
  - npm i -g github-markdown
script: 
  - rm -rf .git
  - bash ./bootstrap.sh
  - git init
  - git config user.name "huangchunwu"
  - git config user.email "951123033@qq.com"
  - git add .
  - git commit -m "update note"
  - git push --force https://$TOKEN@github.com:newhcw/newhcw.github.io.git master
 
env:
  global:
     secure: "AAAAB3NzaC1yc2EAAAADAQABAAABAQDKlI4ha8hLvp4Qn80/chdXwXv8XaVrkiQ1mTWGTPAH02iCQ0Ht0nH4QoY5EpB3u2zpvf8WYvBvFInalfaZ2YhYh4f3l4ajPcRKnJ4vORNRQS0T80m9tf+TnTjOEWs2WIsAxDqObnezEbBYfvjV3y0Q80jeeDDiC8L5jhM7k0MLZK1GLyAtD8Ry4GP2LeWQx5fzRWBx7Y52oQFWNRXOgbVZOvraCJVIlgj0XGFioIV41sLiqXvuenZIbFaXBk1O+igrsDxUWDPVtSe57Xe3fRoscrbSDLy9PfQSVPxZCDdIb61yeaW1NjMdWkJKrTDreGvGgB0OoSEeIgsn/f8/BZrl"
